### ISSUE TITLE
Problem with non-pdf input: execution interrupts, no error returned

### ISSUE THREAD

**Issue by ayuryshev** [gen2brain/go-fitz#23]
On attempt of:

```golang
func Example_NonPDF() {

	buf := bytes.NewBufferString("Non pdf")
	_, err := fitz.NewFromReader(buf)

	// This line never executed. How to caught uncaught error?
	fmt.Printf("fitz.NewFromReader error: %v\n", err)

	// Output: some error expected
}
```
this is printed in stdout:

```
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: no objects found
uncaught error: no objects found
```

Execution interrupts, no error returned.

I suppose that are cgo errors - how to handle them?

**Comment by gen2brain** [comment]
It should be fixed in https://github.com/gen2brain/go-fitz/commit/0adf3f7e5ef80066225b334379f858b56f94dc75, thanks. The other solution was for you to check if data is garbage or valid supported file, but there was already a function for that so I just added a check.

**Comment by ayuryshev** [comment]
Great!
Now it works as expected.

Although I see the same problem with `fitz.New`:

```golang 
func Example_NonPDFFile() {

	_, err := fitz.New("../go.mod")
	fmt.Printf("fitz.New error: %v\n", err)

	// Output: fitz.New error:
}
```

**Comment by gen2brain** [comment]
Check now with https://github.com/gen2brain/go-fitz/commit/072519bd9a7e69b97810d0c2a3f477a8f2fdc6b0 .

**Comment by ayuryshev** [comment]
Hm
```sh
$ cat go.mod|rg go-fitz
        github.com/gen2brain/go-fitz v0.0.0-20201207194431-072519bd9a7e
```
Everythiing correct here?

On attempt to:
```golang
func Example_fitz_NonPDFFile() {

	_, err := fitz.New("../go.mod")
	fmt.Printf("fitz.New error: %v\n", err)

	// Output: fitz.New error:
}
```

I still get:
```
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: no objects found
uncaught error: no objects found
```

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/go-fitz/commit/bea0506ff2266ea99596196417f473c31a10d8df.
